apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-httpd
  labels:
    app: scalable-httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scalable-httpd
  template:
    metadata:
      labels:
        app: scalable-httpd
    spec:
      containers:
      - name: httpd
        image: gcr.io/google-samples/kubernetes-bootcamp:v1      # using the official apache image from docker hub, along with a tag
        ports:
        - containerPort: 8080
